name: Test
on: push

jobs:
    test:
        services:
            ghost:
                image: ghost
                ports:
                    - 2368:2368
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                docker build -t gssg .
            - run: |
                docker run --rm gssg
